### ISSUE TITLE
Expected a symbol for node with kind StringLiteral

### ISSUE THREAD

**Issue by buglas** [ant-galaxy/oasis-engine#51]
### Current Behavior
npm run doc

### Steps to Reproduce

D:\work\webgl\engine\node_modules\typedoc\dist\lib\converter\context.js:56
            throw new Error(`Expected a symbol for node with kind ${ts.SyntaxKind[node.kind]}`);
            ^
Error: Expected a symbol for node with kind StringLiteral
    at Context.expectSymbolAtLocation (D:\work\webgl\engine\node_modules\typedoc\dist\lib\converter\context.js:56:19)
    at ExportDeclarationConverter.convert (D:\work\webgl\engine\node_modules\typedoc\dist\lib\converter\nodes\export.js:98:46)
    at Converter.convertNode (D:\work\webgl\engine\node_modules\typedoc\dist\lib\converter\converter.js:117:53)
    at D:\work\webgl\engine\node_modules\typedoc\dist\lib\converter\nodes\block.js:66:28
    at Array.forEach (<anonymous>)
    at BlockConverter.convertStatements (D:\work\webgl\engine\node_modules\typedoc\dist\lib\converter\nodes\block.js:65:24)
    at D:\work\webgl\engine\node_modules\typedoc\dist\lib\converter\nodes\block.js:44:26
    at Context.withScope (D:\work\webgl\engine\node_modules\typedoc\dist\lib\converter\context.js:109:9)
    at D:\work\webgl\engine\node_modules\typedoc\dist\lib\converter\nodes\block.js:43:25
    at Context.withSourceFile (D:\work\webgl\engine\node_modules\typedoc\dist\lib\converter\context.js:93:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oasis-root@1.0.0 doc: `typedoc --options tools/typedoc/typedoc.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oasis-root@1.0.0 doc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\86136\AppData\Roaming\npm-cache\_logs\2021-02-07T12_30_30_818Z-debug.log

### Environment

- **`Oasis` version**: 0.2.0
- **OS & Version**: win10

**Comment by GuoLei1990** [comment]
The original doc scheme has been abandoned
